config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "yoga_classes#index"

  resources :yoga_classes, only: [ :index, :show ] do
    member do
      get "live"
      post "join_live"
      delete "leave_live"
    end

    # フィードバック関連のルート
    resources :feedbacks, only: [ :new, :create, :show ]
  end

  resources :reservations, only: [ :create, :destroy ]

  # カレンダー関連のルート
  get "calendar", to: "calendars#index"
  get "calendar/day", to: "calendars#day", as: "calendar_day"

  # マイページ関連のルート
  get "mypage", to: "users#show", as: "mypage"
  get "mypage/edit", to: "users#edit", as: "edit_user"
  patch "mypage", to: "users#update"
  get "mypage/password", to: "users#edit_password", as: "edit_user_path_password"
  patch "mypage/password", to: "users#update_password"
  get "mypage/feedbacks", to: "users#feedbacks", as: "user_feedbacks"
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show m-0" role="alert">
    <div class="container">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
  <div class="container-fluid">
    <%= link_to 'オンラインヨガクラス予約システム', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'カレンダー', calendar_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'クラス一覧', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'マイページ', mypage_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <% if user_signed_in? %>
          <span class="navbar-text me-3">
            ようこそ、<%= current_user.username %>さん
          </span>
          <%= button_to 'ログアウト', destroy_user_session_path, 
              method: :delete, 
              data: { confirm: 'ログアウトしますか？' }, 
              class: "btn btn-outline-danger" %>
        <% else %>
          <%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary me-2" %>
          <%= link_to '新規登録', new_user_registration_path, class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>オンラインヨガクラス予約システム</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %><link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
  </head>
  <body>
    <!-- フラッシュメッセージ -->
    <%= render 'layouts/flash_messages' %>
    <!-- ナビゲーションバー -->
    <%= render 'layouts/navbar' %>
    <!-- メインコンテンツ -->
    <div class="container mt-4">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
  </body>
</html>